create table notification_tpls
(
    id            bigint unsigned auto_increment
        primary key,
    notice_id     varchar(255)                null comment '模板唯一标识ID',
    status        tinyint          default 0  not null comment '模板状态:1开启0关闭',
    type          tinyint unsigned default 0  not null comment '通知类型:0系统1微信2短信',
    type_name     varchar(255)     default '' not null comment '类型名称',
    title         varchar(255)     default '' not null comment '标题',
    content       text                        null comment '内容',
    vars          varchar(255)     default '' not null comment '可选的变量',
    template_id   varchar(255)     default '' not null comment '模板ID',
    first_data    varchar(255)     default '' not null comment 'first.DATA',
    keywords_data text                        null comment 'keywords.DATA',
    remark_data   varchar(255)     default '' not null comment 'remark.DATA',
    color         varchar(255)     default '' not null comment 'data color',
    redirect_type tinyint          default 0  not null comment '跳转类型：0无跳转 1跳转H5 2跳转小程序',
    redirect_url  varchar(255)     default '' not null comment '跳转地址',
    page_path     varchar(255)     default '' not null comment '跳转路由',
    is_error      tinyint          default 0  not null comment '模板是否配置错误',
    error_msg     text                        null comment '错误信息',
    push_type     tinyint          default 0  not null comment '消息推送类型(0:即时推送,1:间隔推送)',
    delay_time    int unsigned     default 0  not null comment '间隔推送延迟时间(秒)',
    constraint uk_notice_id
        unique (notice_id)
)
    collate = utf8mb4_unicode_ci
    auto_increment = 103;

INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (1, 'system.registered.passed', 1, 0, '新用户注册通知', '欢迎加入{sitename}', '{username}您好，您已经成为{sitename} 的{groupname} ，请您在发表言论时，遵守本论坛的用户协议，祝您在这里玩的开心哟~', 'a:4:{s:10:"{username}";s:9:"用户名";s:10:"{nickname}";s:6:"昵称";s:10:"{sitename}";s:12:"站点名称";s:11:"{groupname}";s:9:"用户组";}', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (2, 'system.registered.approved', 1, 0, '注册审核通过通知', '注册审核通知', '{username}你好，你的注册申请已审核通过。', 'a:2:{s:10:"{username}";s:9:"用户名";s:10:"{nickname}";s:6:"昵称";}', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (3, 'system.registered.unapproved', 1, 0, '注册审核不通过通知', '注册审核通知', '{username}你好，你的注册申请审核不通过，原因：{reason}', 'a:3:{s:10:"{username}";s:9:"用户名";s:10:"{nickname}";s:6:"昵称";s:8:"{reason}";s:6:"原因";}', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (4, 'system.post.unapproved', 1, 0, '内容审核不通过通知', '内容审核通知', '{username}您好，您发布的 "{content}" 不符合标准，且不可发布。原因：{reason}', 'a:4:{s:10:"{username}";s:9:"用户名";s:10:"{nickname}";s:6:"昵称";s:9:"{content}";s:6:"内容";s:8:"{reason}";s:6:"原因";}', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (5, 'system.post.approved', 1, 0, '内容审核通过通知', '内容审核通知', '{username}您好，您发布的 "{content}" 通过审核，希望您早日成为精品作者。', 'a:3:{s:10:"{username}";s:9:"用户名";s:10:"{nickname}";s:6:"昵称";s:9:"{content}";s:6:"内容";}', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (6, 'system.post.deleted', 1, 0, '内容删除通知', '内容通知', '{username}您好，您发布的 "{content} " 已被下架，原因：{reason}', 'a:4:{s:10:"{username}";s:9:"用户名";s:10:"{nickname}";s:6:"昵称";s:9:"{content}";s:6:"内容";s:8:"{reason}";s:6:"原因";}', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (7, 'system.post.essence', 1, 0, '内容精华通知', '内容通知', '{username}您好，您发布的 "{content}" 已被设为精品帖，您已向精品作者进发。', 'a:3:{s:10:"{username}";s:9:"用户名";s:10:"{nickname}";s:6:"昵称";s:9:"{content}";s:6:"内容";}', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (8, 'system.post.sticky', 1, 0, '内容置顶通知', '内容通知', '{username}你好，你发布的内容 "{content}" 已置顶', 'a:3:{s:10:"{username}";s:9:"用户名";s:10:"{nickname}";s:6:"昵称";s:9:"{content}";s:6:"内容";}', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (9, 'system.post.update', 1, 0, '内容修改通知', '内容通知', '{username}你好，你发布的内容 "{content}" 已被修改', 'a:3:{s:10:"{username}";s:9:"用户名";s:10:"{nickname}";s:6:"昵称";s:9:"{content}";s:6:"内容";}', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (10, 'system.user.disable', 1, 0, '用户禁用通知', '用户通知', '{username}你好，你的帐号已禁用，原因：{reason}', 'a:3:{s:10:"{username}";s:9:"用户名";s:10:"{nickname}";s:6:"昵称";s:8:"{reason}";s:6:"原因";}', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (11, 'system.user.normal', 1, 0, '用户解除禁用通知', '用户通知', '{username}你好，你的帐号已解除禁用', 'a:2:{s:10:"{username}";s:9:"用户名";s:10:"{nickname}";s:6:"昵称";}', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (12, 'system.user.group', 1, 0, '用户角色调整通知', '角色通知', '{username}你好，你的角色由{oldgroupname}变更为{newgroupname}', 'a:4:{s:10:"{username}";s:9:"用户名";s:10:"{nickname}";s:6:"昵称";s:14:"{oldgroupname}";s:12:"老用户组";s:14:"{newgroupname}";s:12:"新用户组";}', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (13, 'system.post.replied', 1, 0, '内容回复通知', '内容通知', '', '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (14, 'system.post.liked', 1, 0, '内容点赞通知', '内容通知', '', '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (15, 'system.post.paid', 1, 0, '内容支付通知', '内容通知', '', '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (16, 'system.post.reminded', 1, 0, '内容@通知', '内容通知', '', '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (17, 'system.withdraw.noticed', 1, 0, '提现通知', '财务通知', '', '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (18, 'system.withdraw.withdraw', 1, 0, '提现失败通知', '财务通知', '', '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (19, 'system.divide.income', 1, 0, '分成收入通知', '内容通知', '', '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (20, 'system.question.asked', 1, 0, '问答提问通知', '问答通知', '', '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (21, 'system.question.answered', 1, 0, '问答回答通知', '问答通知', '', '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (22, 'system.question.expired', 1, 0, '问答过期通知', '内容通知', '', '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (23, 'system.red_packet.gotten', 1, 0, '得到红包通知', '红包通知', '', '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (24, 'system.question.rewarded', 1, 0, '悬赏问答通知', '悬赏通知', '', '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (25, 'system.question.rewarded.expired', 1, 0, '悬赏过期通知', '悬赏通知', '', '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (26, 'wechat.registered.passed', 0, 1, '新用户注册通知', '微信注册通知', null, '', '', '', null, '', '', 0, '', '/pages/home/index', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (27, 'wechat.registered.approved', 0, 1, '注册审核通过通知', '微信注册审核通知', null, '', '', '', null, '', '', 0, '', '/pages/home/index', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (28, 'wechat.registered.unapproved', 0, 1, '注册审核不通过通知', '微信注册审核通知', null, '', '', '', null, '', '', 0, '', '/pages/home/index', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (29, 'wechat.post.approved', 0, 1, '内容审核通过通知', '微信内容审核通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (30, 'wechat.post.unapproved', 0, 1, '内容审核不通过通知', '微信内容审核通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (31, 'wechat.post.deleted', 0, 1, '内容删除通知', '微信内容通知', null, '', '', '', null, '', '', 0, '', '/pages/home/index', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (32, 'wechat.post.essence', 0, 1, '内容精华通知', '微信内容通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (33, 'wechat.post.sticky', 0, 1, '内容置顶通知', '微信内容通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (34, 'wechat.post.update', 0, 1, '内容修改通知', '微信内容通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (35, 'wechat.user.disable', 0, 1, '用户禁用通知', '微信用户通知', null, '', '', '', null, '', '', 0, '', '/pages/notice/notice?title=系统通知&type=system', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (36, 'wechat.user.normal', 0, 1, '用户解除禁用通知', '微信用户通知', null, '', '', '', null, '', '', 0, '', '/pages/notice/notice?title=系统通知&type=system', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (37, 'wechat.user.group', 0, 1, '用户角色调整通知', '微信角色通知', null, '', '', '', null, '', '', 0, '', '/pages/notice/notice?title=系统通知&type=system', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (38, 'wechat.post.replied', 0, 1, '内容回复通知', '微信内容通知', null, '', '', '', null, '', '', 0, '', '/pages/notice/notice?title=回复我的&type=replied', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (39, 'wechat.post.liked', 0, 1, '内容点赞通知', '微信内容通知', null, '', '', '', null, '', '', 0, '', '/pages/notice/notice?title=点赞我的&type=liked', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (40, 'wechat.post.paid', 0, 1, '内容支付通知', '微信内容通知', null, '', '', '', null, '', '', 0, '', '/pages/notice/notice?title=财务通知&type=rewarded,withdrawal', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (41, 'wechat.post.reminded', 0, 1, '内容@通知', '微信内容通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (42, 'wechat.withdraw.noticed', 0, 1, '提现通知', '微信财务通知', null, '', '', '', null, '', '', 0, '', '/pages/my/withdrawalslist', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (43, 'wechat.withdraw.withdraw', 0, 1, '提现失败通知', '微信财务通知', null, '', '', '', null, '', '', 0, '', '/pages/my/withdrawalslist', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (44, 'wechat.divide.income', 0, 1, '分成收入通知', '微信内容通知', null, '', '', '', null, '', '', 0, '', '/pages/my/walletlist', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (45, 'wechat.question.asked', 0, 1, '问答提问通知', '微信问答通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (46, 'wechat.question.answered', 0, 1, '问答回答通知', '微信问答通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (47, 'wechat.question.expired', 0, 1, '问答过期通知', '微信问答通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (48, 'wechat.red_packet.gotten', 0, 1, '得到红包通知', '微信红包通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (49, 'wechat.question.rewarded', 0, 1, '悬赏问答通知', '微信悬赏通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (50, 'wechat.question.rewarded.expired', 0, 1, '悬赏过期通知', '微信悬赏通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (51, 'miniprogram.registered.passed', 0, 4, '新用户注册通知', '小程序注册通知', null, '', '', '', null, '', '', 0, '', '/pages/home/index', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (52, 'miniprogram.registered.approved', 0, 4, '注册审核通过通知', '小程序注册审核通知', null, '', '', '', null, '', '', 0, '', '/pages/home/index', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (53, 'miniprogram.registered.unapproved', 0, 4, '注册审核不通过通知', '小程序注册审核通知', null, '', '', '', null, '', '', 0, '', '/pages/home/index', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (54, 'miniprogram.post.approved', 0, 4, '内容审核通过通知', '小程序内容审核通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (55, 'miniprogram.post.unapproved', 0, 4, '内容审核不通过通知', '小程序内容审核通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (56, 'miniprogram.post.deleted', 0, 4, '内容删除通知', '小程序内容通知', null, '', '', '', null, '', '', 0, '', '/pages/home/index', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (57, 'miniprogram.post.essence', 0, 4, '内容精华通知', '小程序内容通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (58, 'miniprogram.post.sticky', 0, 4, '内容置顶通知', '小程序内容通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (59, 'miniprogram.post.update', 0, 4, '内容修改通知', '小程序内容通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (60, 'miniprogram.user.disable', 0, 4, '用户禁用通知', '小程序用户通知', null, '', '', '', null, '', '', 0, '', '/pages/notice/notice?title=系统通知&type=system', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (61, 'miniprogram.user.normal', 0, 4, '用户解除禁用通知', '小程序用户通知', null, '', '', '', null, '', '', 0, '', '/pages/notice/notice?title=系统通知&type=system', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (62, 'miniprogram.user.group', 0, 4, '用户角色调整通知', '小程序角色通知', null, '', '', '', null, '', '', 0, '', '/pages/notice/notice?title=系统通知&type=system', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (63, 'miniprogram.post.replied', 0, 4, '内容回复通知', '小程序内容通知', null, '', '', '', null, '', '', 0, '', '/pages/notice/notice?title=回复我的&type=replied', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (64, 'miniprogram.post.liked', 0, 4, '内容点赞通知', '小程序内容通知', null, '', '', '', null, '', '', 0, '', '/pages/notice/notice?title=点赞我的&type=liked', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (65, 'miniprogram.post.paid', 0, 4, '内容支付通知', '小程序内容通知', null, '', '', '', null, '', '', 0, '', '/pages/notice/notice?title=财务通知&type=rewarded,withdrawal', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (66, 'miniprogram.post.reminded', 0, 4, '内容@通知', '小程序内容通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (67, 'miniprogram.withdraw.noticed', 0, 4, '提现通知', '小程序财务通知', null, '', '', '', null, '', '', 0, '', '/pages/my/withdrawalslist', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (68, 'miniprogram.withdraw.withdraw', 0, 4, '提现失败通知', '小程序财务通知', null, '', '', '', null, '', '', 0, '', '/pages/my/withdrawalslist', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (69, 'miniprogram.divide.income', 0, 4, '分成收入通知', '小程序内容通知', null, '', '', '', null, '', '', 0, '', '/pages/my/walletlist', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (70, 'miniprogram.question.asked', 0, 4, '问答提问通知', '小程序问答通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (71, 'miniprogram.question.answered', 0, 4, '问答回答通知', '小程序问答通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (72, 'miniprogram.question.expired', 0, 4, '问答过期通知', '小程序问答通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (73, 'miniprogram.red_packet.gotten', 0, 4, '得到红包通知', '小程序红包通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (74, 'miniprogram.question.rewarded', 0, 4, '悬赏问答通知', '小程序悬赏通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (75, 'miniprogram.question.rewarded.expired', 0, 4, '悬赏过期通知', '小程序悬赏通知', null, '', '', '', null, '', '', 0, '', '/topic/index?id={$thread_id}', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (76, 'sms.registered.passed', 0, 2, '新用户注册通知', '短信注册通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (77, 'sms.registered.approved', 0, 2, '注册审核通过通知', '短信注册审核通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (78, 'sms.registered.unapproved', 0, 2, '注册审核不通过通知', '短信注册审核通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (79, 'sms.post.approved', 0, 2, '内容审核通过通知', '短信内容审核通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (80, 'sms.post.unapproved', 0, 2, '内容审核不通过通知', '短信内容审核通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (81, 'sms.post.deleted', 0, 2, '内容删除通知', '短信内容通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (82, 'sms.post.essence', 0, 2, '内容精华通知', '短信内容通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (83, 'sms.post.sticky', 0, 2, '内容置顶通知', '短信内容通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (84, 'sms.post.update', 0, 2, '内容修改通知', '短信内容通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (85, 'sms.user.disable', 0, 2, '用户禁用通知', '短信用户通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (86, 'sms.user.normal', 0, 2, '用户解除禁用通知', '短信用户通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (87, 'sms.user.group', 0, 2, '用户角色调整通知', '短信角色通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (88, 'sms.post.replied', 0, 2, '内容回复通知', '短信内容通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (89, 'sms.post.liked', 0, 2, '内容点赞通知', '短信内容通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (90, 'sms.post.paid', 0, 2, '内容支付通知', '短信内容通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (91, 'sms.post.reminded', 0, 2, '内容@通知', '短信内容通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (92, 'sms.withdraw.noticed', 0, 2, '提现通知', '短信财务通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (93, 'sms.withdraw.withdraw', 0, 2, '提现失败通知', '短信财务通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (94, 'sms.divide.income', 0, 2, '分成收入通知', '短信内容通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (95, 'sms.question.asked', 0, 2, '问答提问通知', '短信问答通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (96, 'sms.question.answered', 0, 2, '问答回答通知', '短信问答通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (97, 'sms.question.expired', 0, 2, '问答过期通知', '短信问答通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (98, 'sms.red_packet.gotten', 0, 2, '得到红包通知', '短信红包通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (99, 'sms.question.rewarded', 0, 2, '悬赏问答通知', '短信悬赏通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (100, 'sms.question.rewarded.expired', 0, 2, '悬赏过期通知', '短信悬赏通知', null, '', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (101, 'system.user.group.upgrade', 1, 0, '用户组升级通知', '账号升级通知', '【{nickname}】恭喜你，成功升级为【{groupname}】！', 'a:2:{s:10:"{nickname}";s:12:"用户昵称";s:11:"{groupname}";s:15:"升级用户组";}', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
INSERT INTO evolve.notification_tpls (id, notice_id, status, type, type_name, title, content, vars, template_id, first_data, keywords_data, remark_data, color, redirect_type, redirect_url, page_path, is_error, error_msg, push_type, delay_time) VALUES (102, 'system.user.group.expired', 1, 0, '站点续费用户组续费通知', '续费通知', '【{nickname}】，您购买的【{groupname}】即将过期，过期后将无法享受当前权益，请及时续费。', 'a:2:{s:10:"{nickname}";s:12:"用户昵称";s:11:"{groupname}";s:12:"老用户组";}', '', '', null, '', '', 0, '', '', 0, null, 0, 0);
